[package]
name = "num_diff"
type = "bin"
authors = [""]

[dependencies]
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }

# Openbanking.nr
openbanking_verifier = { tag = "feat/update-packages_nodash-v0.41.1_and_zkemail", git = "https://github.com/masaun/openbanking.nr-circuit", directory = "./lib" }

# zkEmail
zkemail = { git = "https://github.com/masaun/zkemail.nr", tag = "feat/update-packages_nodash-v0.41.1", directory = "lib" }   # The original zkemail.nr package (version: "zkemail.nr_v.1.0.0-beta.5") with updated dependency (nodash v0.41.1)
sha256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/sha256" } # This module is needed for the zkemail.nr package to work properly along with the nodash v0.41.1.